services:
  # MySQL Database
  database:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ai_resume_parser_development
      MYSQL_USER: ai_resume_parser
      MYSQL_PASSWORD: password
      TZ: Asia/Kolkata
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "ai_resume_parser", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for background jobs (optional but recommended)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Rails Application
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: ai_resume_parser
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      # Ruby AI Service Configuration
      RUBY_AI_SERVICE_URL: http://192.168.65.254:8001
      # AI Service Configuration - Ollama for local development
      OLLAMA_BASE_URL: http://host.docker.internal:11434   # FREE local AI (recommended for dev)
      # Optional: Add other services if needed
      # HUGGINGFACE_API_KEY: hf_your_hugging_face_token    # FREE cloud AI (fallback)
      # OPENAI_API_KEY: sk-your_openai_key_here            # PAID premium AI
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
      - rails_cache:/rails/tmp/cache
      - rails_storage:/rails/storage
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    # Simple startup script that bypasses apartment issues
    command: bash /rails/start_server.sh

  # Background Job Worker (Sidekiq - optional)
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: ai_resume_parser
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      # Ruby AI Service Configuration
      RUBY_AI_SERVICE_URL: http://192.168.65.254:8001
      # AI Service Configuration - Ollama for local development
      OLLAMA_BASE_URL: http://host.docker.internal:11434   # FREE local AI (recommended for dev)
      # Optional: Add other services if needed
      # HUGGINGFACE_API_KEY: hf_your_hugging_face_token    # FREE cloud AI (fallback)
      # OPENAI_API_KEY: sk-your_openai_key_here            # PAID premium AI
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: bundle exec sidekiq

volumes:
  mysql_data:
  redis_data:
  bundle_data:
  rails_cache:
  rails_storage: