# Sidekiq configuration for AI Resume Parser

:concurrency: 2
:timeout: 25
:verbose: true
:queues:
  - critical
  - default
  - low

:scheduler:
  resume_cleanup:
    every: '1d'
    class: ResumeCleanupJob
    queue: low

# Production Redis configuration
:production:
  :redis:
    :url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/0' %>
    :namespace: ai_resume_parser

# Development Redis configuration  
:development:
  :redis:
    :url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/0' %>
    :namespace: ai_resume_parser_dev

# Test Redis configuration
:test:
  :redis:
    :url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>
    :namespace: ai_resume_parser_test