services:
  widget-service:
    build:
      context: ./widget-service
      dockerfile: Dockerfile
    container_name: dashboard-widget-service
    ports:
      - "4005:4005"
    environment:
      - NODE_ENV=development
      - PORT=4005
    restart: unless-stopped